repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
            exclude: ^(reports\/|.*txt$)
          - id: end-of-file-fixer
            exclude: ^(reports\/|.*txt$)
          - id: trailing-whitespace
            exclude: ^(reports\/|.*txt$)

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            types: [python]
            args: ["--line-length", "100"]
    #-   repo: https://github.com/pycqa/pylint
    #    rev: v2.17.2
    #    hooks:
    #    -   id: pylint
    #        types: [python]
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            types: [python]
            # black-compatible isort https://github.com/PyCQA/isort/issues/1518#issuecomment-703056188
            args: ["--profile", "black"]

    - repo: https://github.com/PyCQA/docformatter
      rev: v1.5.0
      hooks:
          - id: docformatter
            types: [python]
            args:
                [
                    "--wrap-summaries=100",
                    "--wrap-descriptions=100",
                    "--make-summary-multi-line",
                    "--pre-summary-newline",
                    "--in-place",
                ]
